-- ============================================================
-- IJAMBO English — seed.sql (généré par scripts/generate-seed.mjs)
-- Plans, paramètres, diagnostic V1, banque de quiz, formation TOEFL démo
-- ============================================================

-- ---------- Passages et scripts audio ----------
insert into public.passages (id, title, body) values ('431dff02-4e53-4b80-9081-6f0b41d6ef01', 'Coffee Cooperatives in the Highlands', 'In the hills of northern Burundi, thousands of small farmers grow arabica coffee on plots often smaller than one hectare. For decades, most of them sold their cherries individually to local traders, accepting whatever price was offered on the day. Over the past fifteen years, however, many farmers have joined washing-station cooperatives. By processing and selling their coffee together, members can negotiate directly with international buyers, share the cost of equipment, and receive training in quality control. Studies of these cooperatives show that member households earn, on average, significantly more per kilogram than non-members. The model is not without challenges: management skills are sometimes limited, and payments to farmers can be delayed. Yet for many rural families, cooperative membership has become the most reliable path to a stable income.');
insert into public.passages (id, title, body) values ('8bf1fbee-7c7a-4c2c-842f-592859d1e941', 'Geothermal Energy in the East African Rift', 'The East African Rift, a zone where the continental plate is slowly pulling apart, offers some of the world''s most promising conditions for geothermal energy. Beneath the Rift''s volcanic corridors, groundwater is heated by shallow magma chambers to temperatures high enough to drive electricity-generating turbines. Kenya, the regional pioneer, already draws a substantial share of its electricity from geothermal plants, and its experience illustrates both the promise and the difficulty of the technology. Exploratory drilling is expensive, and a single well can cost several million dollars with no guarantee of success. Once a productive field is confirmed, however, geothermal plants deliver electricity around the clock, unlike solar or wind installations, and occupy relatively little land. For countries along the Rift seeking to expand access to electricity without increasing carbon emissions, geothermal power therefore represents a strategic, if capital-intensive, opportunity.');
insert into public.passages (id, title, body) values ('857ed2d5-eb43-4813-90fc-adce4be0e1ae', 'Conversation — At the University Library', 'STUDENT: Excuse me, I''d like to borrow these two books on economics, but I don''t have my student card with me today. LIBRARIAN: I''m afraid I can''t check out books without the card. But if you have your student number, I can look you up in the system. STUDENT: Oh, great. It''s B-two-four-one-nine-seven. LIBRARIAN: Let me see… yes, here you are. You can take both books, but be careful — one of them is a reserve copy, so it''s due back in three days, not the usual two weeks. STUDENT: Three days? That''s short. Can I renew it online if I need more time? LIBRARIAN: Only if nobody else has requested it. Reserve copies are in high demand during exam period. STUDENT: Okay, I''ll photocopy the chapter I need tonight, just in case. Thanks a lot!');
insert into public.passages (id, title, body) values ('657fed2d-48b9-4ebe-9835-a738aead2d4b', 'Lecture excerpt — Why Bees Matter to Agriculture', 'PROFESSOR: Today I want to talk about a group of workers that most farmers never pay: pollinators, and especially bees. When a bee visits a flower to collect nectar, pollen sticks to its body and is carried to the next flower. This transfer is what allows many plants to produce fruit and seeds. Now, here''s the number I want you to remember: roughly one third of the food crops we eat depend, at least in part, on animal pollination. Coffee is a good example. Coffee flowers can self-pollinate, so the plant will produce cherries even without bees. But studies across East Africa have shown that when bees are present, coffee yields increase noticeably, and the cherries are larger and more uniform. So pollination is not simply a yes-or-no service; it''s a matter of quality and quantity. That''s why the decline of wild bee populations — driven by pesticide use and habitat loss — is not just an environmental question. It is, very directly, an agricultural and economic one.');
insert into public.passages (id, title, body) values ('73954d18-68d2-4476-948c-59b6e7643524', 'Mobile Money in East Africa', 'Twenty years ago, opening a bank account in rural East Africa often meant travelling for hours to the nearest town and paying fees that few farmers could afford. Today, a basic mobile phone is enough. Mobile money services allow users to deposit, send and receive money through a network of local agents — often the same small shops that sell airtime. The impact has been remarkable: households can receive transfers from relatives in the city within seconds, small traders can pay suppliers without carrying cash, and families can save small amounts safely. Researchers have also noted limits to the system. Agent networks remain thinner in remote areas, transaction fees can weigh heavily on very small transfers, and a mobile account is still not a full substitute for credit. Even so, mobile money has brought millions of people into the financial system for the first time.');
insert into public.passages (id, title, body) values ('b124d1e5-2aea-4e3b-b8ab-3631d9741a97', 'Protecting the Kibira Forest', 'Stretching along the mountain ridge that separates the Congo and Nile river basins, the Kibira forest is one of Burundi''s last large areas of natural montane rainforest. It shelters chimpanzees, colobus monkeys and hundreds of bird species, and it plays a role that goes far beyond wildlife: the forest captures moisture from passing clouds and releases it slowly into the streams that feed farmland and hydroelectric dams downstream. For communities living along its edges, however, the forest has long been a source of firewood, bamboo and new farmland, and population growth has increased this pressure. Conservation programs now try to align local interests with protection. Some hire former forest users as rangers and guides; others support beekeeping at the forest edge, since beekeepers earn more when the forest — and its flowering trees — remains standing. Early results suggest that such approaches slow deforestation more effectively than fences and fines alone.');
insert into public.passages (id, title, body) values ('936f3a55-b7a4-400b-83f4-bb8daf866281', 'Solar Mini-Grids and Rural Electrification', 'For villages located far from national power lines, extending the central grid can cost tens of thousands of dollars per kilometre — a price that utilities rarely recover from customers who consume little electricity. Solar mini-grids offer an alternative. A field of panels, a battery bank and a small local network can supply a whole village with power for lighting, phone charging, refrigeration and small machinery. Costs have fallen sharply as panel and battery prices have dropped, and remote monitoring now allows a single technician to oversee dozens of installations. The economics remain delicate nonetheless. A mini-grid is profitable only if enough households and businesses actually use the electricity, which is why successful operators spend as much effort promoting productive uses — grain mills, welding shops, cold storage — as they do installing hardware. Where such demand develops, mini-grids can transform a village economy; where it does not, the panels risk becoming an expensive monument to good intentions.');
insert into public.passages (id, title, body) values ('bce855ad-1fd3-4d13-8c90-5f8c432e2fda', 'Conversation — Changing a Course Schedule', 'STUDENT: Good morning. I''d like to change one of my courses this semester, if it''s still possible. ADVISOR: The deadline is this Friday, so you''re just in time. Which course? STUDENT: Statistics. It''s at the same time as my English preparation class, and I really can''t miss that one — I''m taking the TOEFL in November. ADVISOR: I see. There''s another statistics section on Tuesday and Thursday mornings, at eight. STUDENT: Eight in the morning… that''s early, but it works. Is it the same professor? ADVISOR: No, it''s Professor Niyonzima. Students say her section moves a bit faster, but she posts all her materials online, which helps. STUDENT: That''s fine with me. What do I need to do? ADVISOR: Fill in a section-change form — I''ll give you one now — and have it signed by the department secretary before Friday at noon. STUDENT: Perfect, I''ll go there right after this. Thank you so much!');
insert into public.passages (id, title, body) values ('95481655-2184-4cad-b969-9bc133d7ee35', 'Lecture excerpt — How Swahili Became a Regional Language', 'PROFESSOR: Let''s turn to one of Africa''s great linguistic success stories: Swahili. Swahili began as a Bantu language spoken in the towns of the East African coast. Its position changed with trade. For centuries, merchants moved goods between the coast and the interior — ivory, salt, copper, cloth — and they needed a common language for negotiation. Swahili filled that role, absorbing vocabulary from Arabic and, later, from Portuguese, Hindi and English along the way. Notice something important here: Swahili did not spread mainly through conquest or through schools. It spread through commerce, because it was useful. Governments came later. In the twentieth century, Tanzania adopted Swahili as a national language and used it in primary education, which standardized the language and gave it prestige. Today, with well over one hundred million speakers and official status in several countries and in the African Union, Swahili is often cited as proof that an African language can serve science, government and higher education. The lesson for linguists is this: languages rise not simply because they are imposed, but because people find them worth using.');

-- ---------- Questions (statut published) ----------
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('6c2a7c25-6b0a-49aa-987a-20f49fcd07a0', 'qcm', 'grammar', 1, 'Choisissez la forme correcte : « My sister ___ at the University of Burundi. »', 'Choose the correct form: "My sister ___ at the University of Burundi."', null, '["study","studies","studying","is study"]'::jsonb, '[1]'::jsonb, 'Au présent simple, la 3e personne du singulier (he/she/it) prend un -s ou -es : she studies. C''est l''erreur la plus fréquente chez les francophones car le français ne marque pas cette distinction à l''oral.', 'In the present simple, the third person singular (he/she/it) takes -s or -es: she studies.', 5, null, array['present-simple','third-person-s','erreur-francophone','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('4a16ad7b-67d6-44a0-8d1a-bce2da529a18', 'qcm', 'grammar', 2, 'Complétez : « I have lived in Gitega ___ 2021. »', 'Complete: "I have lived in Gitega ___ 2021."', null, '["for","since","during","from"]'::jsonb, '[1]'::jsonb, '« Since » s''utilise avec un point de départ précis (since 2021, since Monday) ; « for » avec une durée (for three years). Le français utilise « depuis » dans les deux cas, d''où la confusion fréquente.', '"Since" is used with a starting point (since 2021); "for" with a duration (for three years).', 5, null, array['since-for','present-perfect','erreur-francophone','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('9afd7245-bf97-456c-9d08-55ba16b6084f', 'qcm', 'grammar', 2, 'Quelle phrase est correcte ?', 'Which sentence is correct?', null, '["I will assist to the conference next week.","I will attend the conference next week.","I will assist at the conference next week.","I will attend to the conference next week."]'::jsonb, '[1]'::jsonb, 'Faux ami classique : « assister à » se dit « to attend » (sans préposition). « To assist » signifie « aider ». « I will attend the conference » est la seule forme correcte.', 'False friend: "assister à" translates as "to attend" (no preposition). "To assist" means "to help".', 5, null, array['faux-amis','vocabulary','erreur-francophone','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('3ef747f3-b6f4-4175-a077-016d7f276ee1', 'qcm', 'grammar', 3, 'Complétez : « The reading section was ___ than I expected. »', 'Complete: "The reading section was ___ than I expected."', null, '["more easy","easyer","easier","most easy"]'::jsonb, '[2]'::jsonb, 'Les adjectifs courts (1–2 syllabes) forment leur comparatif en -er : easy → easier (le y devient i). « More easy » est un calque du français « plus facile ».', 'Short adjectives form the comparative with -er: easy → easier. "More easy" is incorrect.', 5, null, array['comparatives','adjectives','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('10597c19-e8b9-4c55-a4f3-40a8a16a4070', 'qcm', 'grammar', 3, 'Complétez : « She ___ her bachelor''s degree in 2023. »', 'Complete: "She ___ her bachelor''s degree in 2023."', null, '["has completed","completed","has been completing","completes"]'::jsonb, '[1]'::jsonb, 'Avec une date passée précise (in 2023), on utilise le prétérit simple : completed. Le present perfect (has completed) est impossible avec un moment daté et révolu — contrairement au passé composé français qui s''emploie dans les deux cas.', 'With a specific past time (in 2023), use the past simple: completed. The present perfect cannot be used with a finished, dated moment.', 5, null, array['past-simple','present-perfect','erreur-francophone','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('5679453c-31bd-4fb0-823a-096c2ba7430c', 'qcm', 'grammar', 4, 'Complétez : « If I ___ a scholarship, I would study in Nairobi. »', 'Complete: "If I ___ a scholarship, I would study in Nairobi."', null, '["will get","would get","got","get"]'::jsonb, '[2]'::jsonb, 'Deuxième conditionnel (situation hypothétique) : If + prétérit, would + base verbale. « If I got a scholarship, I would study… ». Jamais « would » dans la subordonnée en if.', 'Second conditional: If + past simple, would + base verb. Never use "would" in the if-clause.', 5, null, array['conditionals','second-conditional','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('e29a9e98-3995-4fe2-9eea-db7b5eaf5ebd', 'qcm', 'grammar', 4, 'Complétez : « ___ the heavy rain, the graduation ceremony took place outdoors. »', 'Complete: "___ the heavy rain, the graduation ceremony took place outdoors."', null, '["Although","Despite","Even","However"]'::jsonb, '[1]'::jsonb, '« Despite » est suivi d''un nom ou d''un gérondif (despite the rain) ; « although » introduit une proposition complète avec sujet + verbe (although it rained). « However » relie deux phrases indépendantes.', '"Despite" is followed by a noun (despite the rain); "although" introduces a full clause (although it rained).', 5, null, array['connectors','despite-although','toefl-writing-prep','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('2bd7032d-0d46-49ab-9550-7f2d0be03aed', 'qcm', 'grammar', 5, 'Complétez avec le vocabulaire académique approprié : « The experimental results were consistent ___ the initial hypothesis. »', 'Complete with the appropriate academic collocation: "The experimental results were consistent ___ the initial hypothesis."', null, '["to","of","with","at"]'::jsonb, '[2]'::jsonb, 'Collocation académique fixe : « consistent with » (cohérent avec). Les collocations préposition + adjectif sont très testées au TOEFL car elles ne se devinent pas par traduction.', 'Fixed academic collocation: "consistent with". Preposition collocations are frequently tested in TOEFL.', 5, null, array['collocations','academic-vocabulary','toefl-reading-prep','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('98dbffc9-1742-42d0-87c1-b3979a97a300', 'qcm', 'reading', 2, 'Quelle est l''idée principale du passage ?', 'What is the main idea of the passage?', '431dff02-4e53-4b80-9081-6f0b41d6ef01', '["Coffee prices in Burundi are decided by local traders.","Cooperatives help small farmers earn more from their coffee.","Burundian coffee farms are smaller than one hectare.","Cooperative payments to farmers are often delayed."]'::jsonb, '[1]'::jsonb, 'Question de type « main idea » : le passage entier développe les bénéfices des coopératives pour les petits producteurs. Les options A, C et D sont des détails mentionnés, pas l''idée centrale — piège classique du TOEFL.', 'Main-idea question: the passage as a whole develops how cooperatives benefit small farmers. The other options are supporting details.', 5, null, array['main-idea','toefl-reading','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('2a8012b4-7028-44e5-a27a-f93ef4d751e4', 'qcm', 'reading', 3, 'Selon le passage, quel avantage les membres des coopératives obtiennent-ils ?', 'According to the passage, what advantage do cooperative members receive?', '431dff02-4e53-4b80-9081-6f0b41d6ef01', '["Free coffee plants for their plots","Guaranteed payment on the day of delivery","Training in quality control","Larger plots of land"]'::jsonb, '[2]'::jsonb, 'Question de détail : le texte cite explicitement « receive training in quality control ». Les autres options ne sont pas mentionnées — et le texte dit même le contraire pour les paiements (parfois retardés).', 'Detail question: the text explicitly mentions training in quality control. The other options are not stated.', 5, null, array['detail','toefl-reading','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('01d81b4a-a7ca-4646-a77d-68fb4377928f', 'qcm', 'reading', 3, 'Dans le passage, le mot « reliable » est le plus proche de :', 'The word "reliable" in the passage is closest in meaning to:', '431dff02-4e53-4b80-9081-6f0b41d6ef01', '["dependable","profitable","surprising","temporary"]'::jsonb, '[0]'::jsonb, 'Question de vocabulaire en contexte : « reliable » = fiable, sur lequel on peut compter → « dependable ». « Profitable » est un piège plausible dans un texte économique, mais ne correspond pas au sens du mot.', 'Vocabulary-in-context: "reliable" means dependable. "Profitable" is a plausible distractor but does not match the word''s meaning.', 5, null, array['vocabulary-in-context','toefl-reading','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('0b40c996-27c0-4373-918b-59e7a8b58b9a', 'qcm', 'reading', 4, 'Que peut-on déduire du passage à propos de l''énergie solaire ?', 'What can be inferred from the passage about solar energy?', '8bf1fbee-7c7a-4c2c-842f-592859d1e941', '["It is more expensive than geothermal energy.","It does not produce electricity continuously.","It requires drilling expensive wells.","It is not available in the East African Rift."]'::jsonb, '[1]'::jsonb, 'Question d''inférence : le texte dit que les centrales géothermiques produisent « around the clock, unlike solar or wind » — on en déduit que le solaire ne produit pas en continu. L''inférence exige de reformuler une comparaison implicite, compétence clé du TOEFL.', 'Inference question: the passage states geothermal plants run "around the clock, unlike solar or wind", implying solar is not continuous.', 5, null, array['inference','toefl-reading','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('7e5dcd66-1e5a-46ee-ae88-dadfdc1b6f95', 'qcm', 'reading', 5, 'Pourquoi l''auteur mentionne-t-il le Kenya ?', 'Why does the author mention Kenya?', '8bf1fbee-7c7a-4c2c-842f-592859d1e941', '["To argue that Kenya should export electricity to its neighbours","To give an example that shows both the potential and the challenges of geothermal power","To criticize the high cost of exploratory drilling","To compare Kenyan and Burundian energy policies"]'::jsonb, '[1]'::jsonb, 'Question de fonction rhétorique (« why does the author mention… ») : le Kenya sert d''exemple illustrant « both the promise and the difficulty » de la technologie. Il faut identifier le rôle du détail dans l''argumentation, pas seulement son contenu.', 'Rhetorical-purpose question: Kenya is used as an example illustrating both the promise and the difficulty of the technology.', 5, null, array['rhetorical-purpose','toefl-reading','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('98104ae2-d9b8-4644-a1ca-149a36ba7135', 'audio_qcm', 'listening', 2, 'Quel est le problème initial de l''étudiant ?', 'What is the student''s initial problem?', '857ed2d5-eb43-4813-90fc-adce4be0e1ae', '["He does not have his student card with him.","He wants to renew a book online.","The books he needs are not in the library.","He has lost his student number."]'::jsonb, '[0]'::jsonb, 'Question de compréhension globale (gist) : l''étudiant annonce dès la première réplique qu''il n''a pas sa carte d''étudiant. Format typique des conversations campus du TOEFL Listening.', 'Gist question: the student states in his first line that he does not have his student card.', 5, null, array['campus-conversation','gist','toefl-listening','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('92ae6346-6278-40f5-b24b-f6d6230e042a', 'audio_qcm', 'listening', 3, 'Pourquoi l''étudiant décide-t-il de photocopier un chapitre ?', 'Why does the student decide to photocopy a chapter?', '857ed2d5-eb43-4813-90fc-adce4be0e1ae', '["The library is closing soon.","He might not be able to renew the reserve copy.","The book is too heavy to carry.","The librarian asked him to return the book today."]'::jsonb, '[1]'::jsonb, 'Question de détail + lien de cause : la bibliothécaire explique que le renouvellement n''est possible que si personne d''autre ne demande le livre ; l''étudiant photocopie donc « just in case » (au cas où).', 'Detail/cause question: renewal is only possible if no one else requests the book, so he photocopies "just in case".', 5, null, array['campus-conversation','detail','toefl-listening','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('2aff1b88-46f4-46bc-8948-cce651302274', 'audio_qcm', 'listening', 3, 'Que signifie la remarque de la bibliothécaire : « Reserve copies are in high demand during exam period » ?', 'What does the librarian imply when she says: "Reserve copies are in high demand during exam period"?', '857ed2d5-eb43-4813-90fc-adce4be0e1ae', '["The student will probably not be able to keep the book longer.","The library buys more books during exams.","Students are not allowed to borrow reserve copies.","The exam period has already ended."]'::jsonb, '[0]'::jsonb, 'Question pragmatique (ce que le locuteur veut dire sans le dire) : forte demande = faible chance de renouvellement. Le TOEFL teste régulièrement la compréhension de l''implicite.', 'Pragmatic question: high demand implies a low chance of renewal. TOEFL regularly tests implied meaning.', 5, null, array['campus-conversation','pragmatic-understanding','toefl-listening','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('1958e36f-cf0d-4faf-a99c-16f7f48ece8e', 'audio_qcm', 'listening', 4, 'Quel est le sujet principal de cet extrait de cours ?', 'What is the main topic of this lecture excerpt?', '657fed2d-48b9-4ebe-9835-a738aead2d4b', '["How to protect wild bees from pesticides","The role of pollinators in food production","Why coffee plants cannot self-pollinate","The history of beekeeping in East Africa"]'::jsonb, '[1]'::jsonb, 'Question de sujet principal : le cours porte sur le rôle des pollinisateurs dans la production alimentaire ; le café et le déclin des abeilles sont des exemples et conséquences, pas le sujet central. Notez le piège de l''option C, qui contredit le texte (le café PEUT s''autopolliniser).', 'Main-topic question: the lecture is about pollinators'' role in food production. Option C contradicts the lecture.', 5, null, array['academic-lecture','main-idea','toefl-listening','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('39bddca4-5ed0-4781-9618-8c570fd83fd4', 'audio_qcm', 'listening', 5, 'Pourquoi la professeure utilise-t-elle l''exemple du café ?', 'Why does the professor use the example of coffee?', '657fed2d-48b9-4ebe-9835-a738aead2d4b', '["To show that some crops do not need pollinators at all","To show that pollination affects the quality and quantity of a harvest, not only its existence","To explain why coffee prices are rising in East Africa","To compare wild bees with domesticated bees"]'::jsonb, '[1]'::jsonb, 'Question de fonction (« why does the professor say… ») : le café illustre que la pollinisation améliore rendement et qualité même quand elle n''est pas indispensable — « it''s a matter of quality and quantity ». Compétence testée : comprendre le rôle d''un exemple dans un raisonnement académique.', 'Purpose question: coffee illustrates that pollination improves yield and quality even when not strictly required.', 5, null, array['academic-lecture','rhetorical-purpose','toefl-listening','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('6a9d8b6b-9fe5-4c75-bc64-4748574b82b7', 'qcm', 'writing', 3, 'Auto-évaluation — En 30 minutes, pouvez-vous rédiger en anglais un essai structuré d''environ 300 mots (introduction, arguments, conclusion) sur un sujet comme : « Les études à l''étranger apportent-elles plus d''avantages que d''inconvénients ? »', 'Self-assessment — In 30 minutes, can you write a structured essay of about 300 words in English (introduction, arguments, conclusion) on a topic such as: "Does studying abroad bring more advantages than disadvantages?"', null, '["Non, je ne saurais pas par où commencer / No, I would not know where to start","Je peux écrire quelques phrases simples, sans vraie structure / I can write a few simple sentences, without real structure","Je peux écrire un texte structuré, mais avec beaucoup de fautes / I can write a structured text, but with many mistakes","Oui, avec une structure claire et peu de fautes / Yes, with a clear structure and few mistakes"]'::jsonb, '[]'::jsonb, 'Auto-évaluation sans bonne réponse : chaque option rapporte respectivement 0, 2, 3,5 ou 5 points. Le score déclaré oriente le volume de travail Writing recommandé dans votre programme ; il sera recalibré lors du premier test blanc corrigé.', 'Self-assessment: options score 0, 2, 3.5 or 5 points respectively. Recalibrated at the first graded mock test.', 5, '[0,2,3.5,5]'::jsonb, array['self-assessment','writing','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('97ea54c2-18f8-43a4-97f3-e086a4c6087e', 'qcm', 'speaking', 3, 'Auto-évaluation — Pouvez-vous parler en anglais pendant 45 secondes, sans préparation, sur une question comme : « Décrivez un lieu de votre ville que vous recommanderiez à un visiteur, et expliquez pourquoi » ?', 'Self-assessment — Can you speak in English for 45 seconds, without preparation, on a question such as: "Describe a place in your city you would recommend to a visitor, and explain why"?', null, '["Non, je bloque après quelques mots / No, I freeze after a few words","Je peux dire quelques phrases avec de longues pauses / I can say a few sentences with long pauses","Je peux parler 45 secondes, mais avec des hésitations et des fautes / I can speak for 45 seconds, but with hesitations and mistakes","Oui, de façon fluide et organisée / Yes, fluently and in an organized way"]'::jsonb, '[]'::jsonb, 'Auto-évaluation sans bonne réponse : options notées 0, 2, 3,5 ou 5 points. Le Speaking est la section où l''auto-évaluation des francophones est la moins fiable — elle sera systématiquement recalibrée lors de la première session live ou avec le coach.', 'Self-assessment: options score 0, 2, 3.5 or 5 points. Recalibrated at the first live session or with the coach.', 5, '[0,2,3.5,5]'::jsonb, array['self-assessment','speaking','diagnostic-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('4ddf3e4d-afd5-48fe-a4cd-1f13236f1f2d', 'qcm', 'grammar', 1, 'Complétez : « Right now, the students ___ for the exam. »', 'Complete: "Right now, the students ___ for the exam."', null, '["study","are studying","studies","studied"]'::jsonb, '[1]'::jsonb, '« Right now » signale une action en cours → présent continu : are studying.', '"Right now" signals an action in progress → present continuous.', 1, null, array['present-continuous','lesson-tenses-1','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('6a6ee5d0-dc1f-41e4-b2dd-0d4bacaec9dc', 'qcm', 'grammar', 1, 'Complétez : « She wants to become ___ engineer. »', 'Complete: "She wants to become ___ engineer."', null, '["a","an","the","—"]'::jsonb, '[1]'::jsonb, '« An » devant un son voyelle : an engineer. Le choix se fait sur le son, pas la lettre.', '"An" before a vowel sound: an engineer.', 1, null, array['articles','lesson-articles','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('10172220-a8ad-4dd8-a177-0617d226b949', 'qcm', 'grammar', 1, 'Complétez : « How many ___ attended the conference? »', 'Complete: "How many ___ attended the conference?"', null, '["persons","peoples","people","person"]'::jsonb, '[2]'::jsonb, '« People » est le pluriel courant de « person ». « Peoples » ne s''emploie que pour désigner des peuples/nations.', '"People" is the standard plural of "person". "Peoples" refers to nations.', 1, null, array['irregular-plurals','lesson-nouns','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('c69a2a16-b7bb-4b88-9302-ec889085587f', 'qcm', 'grammar', 1, 'Complétez : « The class starts ___ 8 a.m. »', 'Complete: "The class starts ___ 8 a.m."', null, '["in","on","at","to"]'::jsonb, '[2]'::jsonb, 'Heure précise → « at » (at 8 a.m.). « In » pour les mois/années, « on » pour les jours.', 'Precise time → "at". "In" for months/years, "on" for days.', 1, null, array['prepositions-time','lesson-prepositions','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('456fa89f-6607-4cf4-8f1a-79cf941f6d59', 'qcm', 'grammar', 2, 'Complétez : « I''m very interested ___ economics. »', 'Complete: "I''m very interested ___ economics."', null, '["by","in","at","for"]'::jsonb, '[1]'::jsonb, 'Collocation fixe : interested in. Le français « intéressé par » induit l''erreur « by ».', 'Fixed collocation: interested in.', 1, null, array['prepositions-adjectives','erreur-francophone','lesson-prepositions','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('efd55994-3b11-4cbb-b48e-a037d649ef86', 'qcm', 'grammar', 1, 'Complétez : « We don''t have ___ questions. »', 'Complete: "We don''t have ___ questions."', null, '["some","any","no","a"]'::jsonb, '[1]'::jsonb, 'Phrase négative → « any ». « Some » s''emploie dans les affirmatives, « no » avec un verbe positif (we have no questions).', 'Negative sentence → "any".', 1, null, array['some-any','lesson-quantifiers','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('f0123a75-43c5-4734-a8ef-54087d27c485', 'qcm', 'grammar', 1, 'Complétez : « They ___ to Gitega last week. »', 'Complete: "They ___ to Gitega last week."', null, '["go","goed","went","gone"]'::jsonb, '[2]'::jsonb, 'Prétérit irrégulier : go → went. « Gone » est le participe passé (have gone).', 'Irregular past: go → went.', 1, null, array['past-simple','irregular-verbs','lesson-tenses-2','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('dd4ffdd3-92d1-412f-bda5-be24f8a79bc6', 'qcm', 'grammar', 2, 'Complétez : « I have never ___ in an airplane. »', 'Complete: "I have never ___ in an airplane."', null, '["flew","flown","fly","flying"]'::jsonb, '[1]'::jsonb, 'Present perfect → participe passé : fly / flew / flown. « Never » se place entre have et le participe.', 'Present perfect → past participle: flown.', 1, null, array['present-perfect','irregular-verbs','lesson-tenses-3','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('1c33c847-5140-424a-aa04-234b29c87951', 'qcm', 'grammar', 2, 'Complétez : « Look at those clouds! It ___ rain. »', 'Complete: "Look at those clouds! It ___ rain."', null, '["will","is going to","would","shall"]'::jsonb, '[1]'::jsonb, 'Prédiction fondée sur un indice visible → be going to. « Will » exprime une prédiction générale ou une décision spontanée.', 'Prediction based on visible evidence → be going to.', 1, null, array['future-forms','lesson-future','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('12c1ad93-7e48-4e20-aa83-d49f6082a003', 'qcm', 'grammar', 3, 'Complétez : « The phone is ringing — I ___ answer it. »', 'Complete: "The phone is ringing — I ___ answer it."', null, '["am going to","will","would","am"]'::jsonb, '[1]'::jsonb, 'Décision prise à l''instant → will. « Going to » exprime une intention déjà planifiée.', 'Spontaneous decision → will.', 1, null, array['future-forms','lesson-future','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('75a885c7-4081-453a-b493-179cdbaafcc2', 'qcm', 'grammar', 2, 'Complétez : « Candidates ___ bring their ID to the exam. It is compulsory. »', 'Complete: "Candidates ___ bring their ID to the exam. It is compulsory."', null, '["should","must","can","might"]'::jsonb, '[1]'::jsonb, 'Obligation forte (compulsory) → must. « Should » n''est qu''un conseil.', 'Strong obligation → must. "Should" is only advice.', 1, null, array['modals-obligation','lesson-modals','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('0fe20d39-5bec-485d-85cb-ec0163aaf72b', 'qcm', 'grammar', 4, 'Complétez : « She''s not answering her phone; she ___ be in class. »', 'Complete: "She''s not answering her phone; she ___ be in class."', null, '["can","must","would","shall"]'::jsonb, '[1]'::jsonb, 'Déduction logique quasi certaine → must (elle doit être en cours). Usage épistémique des modaux, très testé au TOEFL.', 'Logical deduction → must (epistemic use).', 1, null, array['modals-deduction','lesson-modals','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('f9660f6a-fb09-4092-b1b0-a62142a6f750', 'qcm', 'grammar', 2, 'Complétez : « This is ___ question I have ever seen. »', 'Complete: "This is ___ question I have ever seen."', null, '["the more difficult","most difficult","the most difficult","difficulter"]'::jsonb, '[2]'::jsonb, 'Superlatif d''un adjectif long : the most + adjectif. Ne pas oublier « the ».', 'Superlative of a long adjective: the most + adjective.', 1, null, array['superlatives','lesson-comparatives','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('a7097e44-dcff-4751-9867-36af573c2268', 'qcm', 'grammar', 1, 'Complétez : « How ___ money do you need for the registration? »', 'Complete: "How ___ money do you need for the registration?"', null, '["many","much","few","lot"]'::jsonb, '[1]'::jsonb, '« Money » est indénombrable → how much. « How many » pour les dénombrables (how many books).', '"Money" is uncountable → how much.', 1, null, array['countable-uncountable','lesson-quantifiers','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('82ac74a6-1ef3-441f-819e-35890fd16c1c', 'qcm', 'grammar', 2, 'Complétez : « Hurry up — we have very ___ time left. »', 'Complete: "Hurry up — we have very ___ time left."', null, '["few","little","less","small"]'::jsonb, '[1]'::jsonb, '« Time » est indénombrable → little. « Few » s''emploie avec les dénombrables (few minutes).', '"Time" is uncountable → little.', 1, null, array['few-little','lesson-quantifiers','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('f86cbd9f-cc8f-4922-a272-d114b09ffc5e', 'qcm', 'grammar', 3, 'Complétez : « English ___ in many East African schools. »', 'Complete: "English ___ in many East African schools."', null, '["teaches","is taught","is teaching","taught"]'::jsonb, '[1]'::jsonb, 'Voix passive au présent : be + participe passé → is taught. Le sujet (English) subit l''action.', 'Present passive: be + past participle → is taught.', 1, null, array['passive-voice','lesson-passive','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('f3bfdf8f-361f-419b-8f9e-47d810fbbf44', 'qcm', 'grammar', 3, 'Complétez : « The results ___ published yesterday. »', 'Complete: "The results ___ published yesterday."', null, '["was","were","have been","are"]'::jsonb, '[1]'::jsonb, 'Passif au prétérit avec sujet pluriel (results) + moment daté (yesterday) → were published.', 'Past passive with plural subject and dated moment → were published.', 1, null, array['passive-voice','past-simple','lesson-passive','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('7a34fa28-0b31-4ad5-b18c-28308238d206', 'qcm', 'grammar', 2, 'Complétez : « The student ___ won the scholarship is from Ngozi. »', 'Complete: "The student ___ won the scholarship is from Ngozi."', null, '["which","who","whose","whom"]'::jsonb, '[1]'::jsonb, 'Antécédent humain + fonction sujet → who. « Which » pour les choses, « whose » pour la possession.', 'Human antecedent + subject role → who.', 1, null, array['relative-clauses','lesson-relatives','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('8aa520ca-1565-4ff8-8e71-953d2f4b1541', 'qcm', 'grammar', 4, 'Complétez : « The professor ___ course I attend on Mondays wrote this book. »', 'Complete: "The professor ___ course I attend on Mondays wrote this book."', null, '["who","which","whose","that"]'::jsonb, '[2]'::jsonb, 'Relation de possession (le cours DU professeur) → whose. Équivalent de « dont » en français.', 'Possessive relation → whose.', 1, null, array['relative-clauses','whose','lesson-relatives','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('a98d89c6-e79e-435f-9f59-f1b80acb7f82', 'qcm', 'grammar', 2, 'Complétez : « She enjoys ___ podcasts in English. »', 'Complete: "She enjoys ___ podcasts in English."', null, '["to listen to","listening to","listen","to listening"]'::jsonb, '[1]'::jsonb, '« Enjoy » est toujours suivi du gérondif : enjoy + V-ing. À mémoriser avec avoid, finish, mind, suggest.', '"Enjoy" is always followed by the gerund: enjoy + V-ing.', 1, null, array['gerund-infinitive','lesson-gerund','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('ff49bff8-ad54-4909-88a6-8ac30d777897', 'qcm', 'grammar', 2, 'Complétez : « He moved to Nairobi ___ medicine. »', 'Complete: "He moved to Nairobi ___ medicine."', null, '["for study","for studying","to study","study"]'::jsonb, '[2]'::jsonb, 'But/objectif → infinitif avec to : to study. « For + V-ing » exprime la fonction d''un objet, pas le but d''une action. Calque fréquent du français « pour étudier ».', 'Purpose → to + infinitive. "For + V-ing" expresses an object''s function.', 1, null, array['infinitive-purpose','erreur-francophone','lesson-gerund','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('cfcb85af-badf-4125-a975-13467e843333', 'qcm', 'grammar', 2, 'Complétez : « If you practice every day, you ___ quickly. »', 'Complete: "If you practice every day, you ___ quickly."', null, '["would improve","will improve","improved","improving"]'::jsonb, '[1]'::jsonb, 'Premier conditionnel (situation réelle/probable) : If + présent, will + base verbale.', 'First conditional: If + present, will + base verb.', 1, null, array['conditionals','first-conditional','lesson-conditionals','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('ac15648c-97e4-438e-8677-f72ed44c0336', 'qcm', 'grammar', 5, 'Complétez : « If she had applied earlier, she ___ the scholarship. »', 'Complete: "If she had applied earlier, she ___ the scholarship."', null, '["would receive","will have received","would have received","had received"]'::jsonb, '[2]'::jsonb, 'Troisième conditionnel (regret sur le passé) : If + past perfect, would have + participe passé.', 'Third conditional: If + past perfect, would have + past participle.', 1, null, array['conditionals','third-conditional','lesson-conditionals','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('92a11124-6334-427b-84fd-3d251c9b99a9', 'qcm', 'grammar', 3, 'Discours rapporté : « I am tired », he said. → He said he ___ tired.', 'Reported speech: "I am tired", he said. → He said he ___ tired.', null, '["is","was","has been","were"]'::jsonb, '[1]'::jsonb, 'Au discours rapporté après un verbe au passé, les temps reculent : am → was (backshift).', 'In reported speech after a past verb, tenses shift back: am → was.', 1, null, array['reported-speech','lesson-reported','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('30510d41-1798-412a-97c7-d24bce975ee1', 'qcm', 'grammar', 3, 'Complétez : « You''re taking the TOEFL in June, ___? »', 'Complete: "You''re taking the TOEFL in June, ___?"', null, '["isn''t it","aren''t you","don''t you","won''t you"]'::jsonb, '[1]'::jsonb, 'Question tag : reprise de l''auxiliaire (are) à la forme inverse + sujet → aren''t you. « Isn''t it » est un calque du « n''est-ce pas » français.', 'Question tag: repeat the auxiliary in the opposite form → aren''t you.', 1, null, array['question-tags','erreur-francophone','lesson-questions','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('b0ed88ed-a0e3-4b88-a0bd-92d4c6f98c6b', 'qcm', 'grammar', 2, 'Complétez : « Please ___ the application form before Friday. »', 'Complete: "Please ___ the application form before Friday."', null, '["fill in","fill on","fulfill","full in"]'::jsonb, '[0]'::jsonb, 'Phrasal verb : fill in (ou fill out) = remplir un formulaire. « Fulfill » = accomplir (une promesse, une condition).', 'Phrasal verb: fill in (or fill out) = complete a form.', 1, null, array['phrasal-verbs','lesson-phrasal-verbs','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('907300ec-9054-46a7-b386-38b67c9bd341', 'qcm', 'grammar', 3, 'Que signifie « actually » dans : « Actually, the library closes at 6, not at 8. » ?', 'What does "actually" mean in: "Actually, the library closes at 6, not at 8."?', null, '["Actuellement / currently","En fait / in fact","Rapidement / quickly","Officiellement / officially"]'::jsonb, '[1]'::jsonb, 'Faux ami majeur : « actually » = en fait, en réalité. « Actuellement » se dit currently ou at the moment.', 'Major false friend: "actually" = in fact. "Actuellement" = currently.', 1, null, array['faux-amis','vocabulary','erreur-francophone','lesson-vocabulary-1','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('f02320ef-84a2-4ef6-a2d9-cf25e68af2b3', 'qcm', 'grammar', 3, 'Complétez : « The company made a significant ___ in solar energy. »', 'Complete: "The company made a significant ___ in solar energy."', null, '["invest","investment","investor","invested"]'::jsonb, '[1]'::jsonb, 'Après un adjectif (significant), il faut un nom : investment. Les questions de dérivation (verbe/nom/adjectif) sont fréquentes au TOEFL.', 'After an adjective, a noun is needed: investment (word-form question).', 1, null, array['word-forms','lesson-vocabulary-2','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('9150856a-2465-4ad1-8b7e-03cb7d2c3a52', 'qcm', 'grammar', 4, 'Complétez : « The program is affordable; ___, it includes personal coaching. »', 'Complete: "The program is affordable; ___, it includes personal coaching."', null, '["however","moreover","although","despite"]'::jsonb, '[1]'::jsonb, 'Les deux idées vont dans le même sens (addition) → moreover (de plus). « However » marque l''opposition.', 'Both ideas point the same way (addition) → moreover.', 1, null, array['connectors','lesson-connectors','toefl-writing-prep','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('4c263ca9-98b8-43c2-b3d8-0c4f9f4f51a9', 'qcm', 'grammar', 4, 'Complétez : « The study ___ a strong link between sleep and memory. »', 'Complete: "The study ___ a strong link between sleep and memory."', null, '["did","made","found","said"]'::jsonb, '[2]'::jsonb, 'Collocation académique : a study finds / shows / reveals a link. « Make » et « do » ne se combinent pas avec « link ».', 'Academic collocation: a study finds/shows a link.', 1, null, array['collocations','academic-vocabulary','lesson-vocabulary-2','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('a66fa1d8-b567-4de7-a334-ff4df4fba3af', 'qcm', 'reading', 2, 'Quelle est l''idée principale du passage ?', 'What is the main idea of the passage?', '73954d18-68d2-4476-948c-59b6e7643524', '["Mobile money has expanded financial access in East Africa despite some limits.","Banks in East Africa have lowered their fees for farmers.","Mobile money agents earn more than small traders.","Transaction fees make mobile money useless for families."]'::jsonb, '[0]'::jsonb, 'Le passage présente l''essor du mobile money, ses bénéfices puis ses limites — l''option A résume cet équilibre. Les autres déforment ou isolent un détail.', 'The passage presents mobile money''s rise, benefits, then limits — option A captures that balance.', 1, null, array['main-idea','toefl-reading','lesson-reading-main-idea','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('5b77a7cc-7936-4f10-8975-8d967a7b9b21', 'qcm', 'reading', 2, 'Selon le passage, qui joue souvent le rôle d''agents de mobile money ?', 'According to the passage, who often serves as mobile money agents?', '73954d18-68d2-4476-948c-59b6e7643524', '["Bank employees","Local shops that sell airtime","Government offices","Farmers'' cooperatives"]'::jsonb, '[1]'::jsonb, 'Détail explicite : « often the same small shops that sell airtime ».', 'Explicit detail: the small shops that sell airtime.', 1, null, array['detail','toefl-reading','lesson-reading-details','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('cb91231b-35e5-4231-9152-e6c4d20e9d12', 'qcm', 'reading', 3, 'Dans le passage, le mot « remarkable » est le plus proche de :', 'The word "remarkable" in the passage is closest in meaning to:', '73954d18-68d2-4476-948c-59b6e7643524', '["impressive","doubtful","expensive","temporary"]'::jsonb, '[0]'::jsonb, '« Remarkable » = remarquable, impressionnant → impressive. Le contexte (liste de bénéfices) confirme le sens positif.', '"Remarkable" means impressive; the positive context confirms it.', 1, null, array['vocabulary-in-context','toefl-reading','lesson-reading-vocabulary','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('11c0fae8-e1b1-4bc1-a8db-686a90cea493', 'qcm', 'reading', 4, 'Tous les éléments suivants sont cités comme limites du mobile money SAUF :', 'All of the following are mentioned as limits of mobile money EXCEPT:', '73954d18-68d2-4476-948c-59b6e7643524', '["Thinner agent networks in remote areas","Fees that weigh on small transfers","The absence of a full credit substitute","The risk of phone theft"]'::jsonb, '[3]'::jsonb, 'Question « negative fact » (EXCEPT) : trois limites sont citées ; le vol de téléphone n''est jamais mentionné. Ce format inversé piège les lecteurs pressés — lisez toujours la consigne deux fois.', 'Negative-fact question: phone theft is never mentioned in the passage.', 1, null, array['negative-fact','toefl-reading','lesson-reading-details','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('336de509-3ca8-4d0b-9215-84d40c567a55', 'qcm', 'reading', 3, 'Quelle est l''idée principale du passage ?', 'What is the main idea of the passage?', 'b124d1e5-2aea-4e3b-b8ab-3631d9741a97', '["The Kibira forest is home to chimpanzees and rare birds.","Conservation works best when local communities benefit from protecting the forest.","Population growth should be limited near protected areas.","Hydroelectric dams depend entirely on the Kibira forest."]'::jsonb, '[1]'::jsonb, 'Le passage progresse vers sa conclusion : les programmes qui alignent intérêts locaux et protection sont les plus efficaces. Les options A et D sont des détails ; C n''est pas affirmé.', 'The passage builds toward its conclusion: aligning local interests with protection works best.', 1, null, array['main-idea','toefl-reading','lesson-reading-main-idea','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('8802cbdf-5e7e-4588-9095-74b3e828757f', 'qcm', 'reading', 3, 'Selon le passage, pourquoi les apiculteurs ont-ils intérêt à protéger la forêt ?', 'According to the passage, why do beekeepers have an interest in protecting the forest?', 'b124d1e5-2aea-4e3b-b8ab-3631d9741a97', '["They earn more when the flowering trees remain standing.","They receive fines when trees are cut.","They sell firewood collected in the forest.","They work as rangers during the dry season."]'::jsonb, '[0]'::jsonb, 'Détail explicite : les apiculteurs gagnent davantage quand la forêt et ses arbres en fleurs restent debout.', 'Explicit detail: beekeepers earn more when the forest and its flowering trees remain standing.', 1, null, array['detail','toefl-reading','lesson-reading-details','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('bb4b75f4-b433-4fd6-ade9-5a37e71266dc', 'qcm', 'reading', 4, 'Que peut-on déduire du passage à propos des « fences and fines » (clôtures et amendes) ?', 'What can be inferred about "fences and fines"?', 'b124d1e5-2aea-4e3b-b8ab-3631d9741a97', '["They were the traditional approach to conservation before the new programs.","They have been completely abandoned in Burundi.","They are more expensive than hiring rangers.","They were invented by the conservation programs described."]'::jsonb, '[0]'::jsonb, 'Inférence : comparer les nouvelles approches à « fences and fines alone » implique que clôtures et amendes constituaient l''approche antérieure de référence. Les options B et C vont au-delà du texte.', 'Inference: comparing new approaches to "fences and fines alone" implies these were the prior standard approach.', 1, null, array['inference','toefl-reading','lesson-reading-inference','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('ab753a81-4464-4d3a-8674-0cd1b242470d', 'qcm', 'reading', 4, 'Dans le passage, le mot « align » est le plus proche de :', 'The word "align" in the passage is closest in meaning to:', 'b124d1e5-2aea-4e3b-b8ab-3631d9741a97', '["bring into agreement","measure precisely","separate clearly","reduce gradually"]'::jsonb, '[0]'::jsonb, '« Align local interests with protection » = faire coïncider les intérêts locaux avec la protection → bring into agreement.', '"Align interests with protection" = bring them into agreement.', 1, null, array['vocabulary-in-context','toefl-reading','lesson-reading-vocabulary','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('b3fe191d-17e3-4569-b570-5d267602537a', 'qcm', 'reading', 4, 'Pourquoi l''auteur mentionne-t-il les moulins à grain, les ateliers de soudure et les chambres froides ?', 'Why does the author mention grain mills, welding shops and cold storage?', '936f3a55-b7a4-400b-83f4-bb8daf866281', '["To give examples of productive uses that make a mini-grid profitable","To list the equipment included in every mini-grid","To show that villages prefer machinery to lighting","To criticize operators who install too much hardware"]'::jsonb, '[0]'::jsonb, 'Fonction rhétorique : ces exemples illustrent les « productive uses » qui créent la demande nécessaire à la rentabilité.', 'Rhetorical purpose: examples of the productive uses that create sufficient demand.', 1, null, array['rhetorical-purpose','toefl-reading','lesson-reading-inference','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('2a632f85-64b7-426d-a7b6-602927dda3d9', 'qcm', 'reading', 4, 'Selon le passage, qu''est-ce qui a rendu les mini-réseaux plus abordables ?', 'According to the passage, what has made mini-grids more affordable?', '936f3a55-b7a4-400b-83f4-bb8daf866281', '["Falling panel and battery prices","Government subsidies to utilities","Higher electricity consumption in villages","Cheaper national power lines"]'::jsonb, '[0]'::jsonb, 'Détail explicite : « Costs have fallen sharply as panel and battery prices have dropped ».', 'Explicit detail: costs fell as panel and battery prices dropped.', 1, null, array['detail','toefl-reading','lesson-reading-details','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('0ef112e5-f1c1-4f03-8b55-3ddaac6f020e', 'qcm', 'reading', 5, 'Que suggère l''expression « an expensive monument to good intentions » ?', 'What does the phrase "an expensive monument to good intentions" suggest?', '936f3a55-b7a4-400b-83f4-bb8daf866281', '["A mini-grid without sufficient demand becomes a costly failure.","Villages build monuments to celebrate electrification.","Good intentions are more important than profitability.","Operators should spend more on hardware."]'::jsonb, '[0]'::jsonb, 'Langage figuré : un « monument aux bonnes intentions » désigne ironiquement un projet coûteux devenu inutile. Le TOEFL teste la compréhension des expressions imagées en contexte.', 'Figurative language: an ironic image for a costly, unused project.', 1, null, array['inference','figurative-language','toefl-reading','lesson-reading-inference','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('5b0bb652-8487-4640-8cea-d16cbd2648a9', 'qcm', 'reading', 5, 'Quelle affirmation résume le mieux la position de l''auteur ?', 'Which statement best summarizes the author''s position?', '936f3a55-b7a4-400b-83f4-bb8daf866281', '["Mini-grids are promising, but their success depends on developing local demand.","Extending the national grid is always the better solution.","Mini-grids are profitable in every village where they are installed.","Remote monitoring is the main obstacle to rural electrification."]'::jsonb, '[0]'::jsonb, 'Synthèse de l''argumentation : potentiel réel + condition de succès (la demande). Les autres options contredisent le texte.', 'Summary of the argument: real potential, conditional on local demand.', 1, null, array['summary','toefl-reading','lesson-reading-main-idea','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('c5e05507-9571-44f6-bb5c-3c3ebf8ed6b2', 'audio_qcm', 'listening', 2, 'Pourquoi l''étudiante veut-elle changer de cours ?', 'Why does the student want to change her course?', 'bce855ad-1fd3-4d13-8c90-5f8c432e2fda', '["Statistics conflicts with her English preparation class.","She finds statistics too difficult.","She prefers Professor Niyonzima.","She missed the registration deadline."]'::jsonb, '[0]'::jsonb, 'Compréhension globale : le cours de statistiques est au même horaire que sa préparation d''anglais, qu''elle ne peut pas manquer.', 'Gist: statistics conflicts with her English preparation class.', 1, null, array['campus-conversation','gist','toefl-listening','lesson-listening-conversations','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('b23f1022-3aa4-4ed8-8dc0-7d0793754c7c', 'audio_qcm', 'listening', 3, 'Que doit faire l''étudiante avant vendredi midi ?', 'What must the student do before Friday at noon?', 'bce855ad-1fd3-4d13-8c90-5f8c432e2fda', '["Have a form signed by the department secretary","Email Professor Niyonzima","Register for the TOEFL","Attend the Tuesday statistics class"]'::jsonb, '[0]'::jsonb, 'Détail : remplir le formulaire ET le faire signer par la secrétaire du département avant vendredi midi.', 'Detail: have the section-change form signed by the department secretary before Friday noon.', 1, null, array['campus-conversation','detail','toefl-listening','lesson-listening-conversations','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('a7d34d09-7589-4d75-a911-f9693905595c', 'audio_qcm', 'listening', 4, 'Que sous-entend le conseiller en disant que la professeure « posts all her materials online, which helps » ?', 'What does the advisor imply by saying the professor "posts all her materials online, which helps"?', 'bce855ad-1fd3-4d13-8c90-5f8c432e2fda', '["The online materials compensate for the faster pace of the section.","Students never need to attend her classes.","The professor prefers teaching online.","The materials are only available to advisors."]'::jsonb, '[0]'::jsonb, 'Compréhension pragmatique : « which helps » relie les supports en ligne au rythme plus rapide — ils aident à suivre malgré ce rythme.', 'Pragmatic understanding: the online materials help students cope with the faster pace.', 1, null, array['campus-conversation','pragmatic-understanding','toefl-listening','lesson-listening-conversations','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('6fd61969-722e-4ab9-8cf5-ee02b0283b28', 'audio_qcm', 'listening', 3, 'Quelle est l''attitude de l''étudiante face au cours de 8 heures du matin ?', 'What is the student''s attitude toward the eight o''clock class?', 'bce855ad-1fd3-4d13-8c90-5f8c432e2fda', '["It is early, but she accepts it.","She refuses to wake up that early.","She thinks it is the perfect time.","She wants to check with her parents first."]'::jsonb, '[0]'::jsonb, 'Question d''attitude : « that''s early, but it works » — réserve suivie d''une acceptation. Le ton et les nuances du locuteur sont explicitement testés au TOEFL.', 'Attitude question: "that''s early, but it works" — reservation followed by acceptance.', 1, null, array['campus-conversation','attitude','toefl-listening','lesson-listening-conversations','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('3ca356ce-84b6-4ff1-8bfe-5c719776fef4', 'audio_qcm', 'listening', 4, 'Quel est le sujet principal de cet extrait de cours ?', 'What is the main topic of this lecture excerpt?', '95481655-2184-4cad-b969-9bc133d7ee35', '["How trade and later policy spread the Swahili language","Why Arabic replaced Bantu languages on the coast","The role of schools in eliminating local languages","The differences between Swahili and English grammar"]'::jsonb, '[0]'::jsonb, 'Sujet principal : la diffusion du swahili, d''abord par le commerce, puis renforcée par les politiques publiques.', 'Main topic: the spread of Swahili, first through trade, then reinforced by policy.', 1, null, array['academic-lecture','main-idea','toefl-listening','lesson-listening-lectures','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('fc78c8bb-1105-40b4-8099-9bcea821d8be', 'audio_qcm', 'listening', 4, 'Selon le professeur, pourquoi le swahili s''est-il d''abord répandu ?', 'According to the professor, why did Swahili first spread?', '95481655-2184-4cad-b969-9bc133d7ee35', '["Because merchants needed a common language for trade","Because it was imposed by colonial schools","Because Tanzania made it a national language","Because it replaced Arabic in religious texts"]'::jsonb, '[0]'::jsonb, 'Détail central : le swahili s''est répandu par le commerce (« It spread through commerce, because it was useful »), avant toute politique d''État.', 'Key detail: Swahili spread through commerce because it was useful.', 1, null, array['academic-lecture','detail','toefl-listening','lesson-listening-lectures','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('bf4b9125-162a-42a1-bbc6-a639c430a1e0', 'audio_qcm', 'listening', 5, 'Pourquoi le professeur dit-il « Notice something important here » ?', 'Why does the professor say "Notice something important here"?', '95481655-2184-4cad-b969-9bc133d7ee35', '["To draw attention to a point that contradicts a common assumption","To announce the end of the lecture","To ask students a question about vocabulary","To correct a mistake he made earlier"]'::jsonb, '[0]'::jsonb, 'Fonction du discours : le professeur signale un point contre-intuitif (diffusion par le commerce, pas par la conquête ou l''école). Repérer ces marqueurs de structure est une compétence clé du TOEFL Listening.', 'Discourse function: the professor flags a counter-intuitive point (spread through commerce, not conquest).', 1, null, array['academic-lecture','rhetorical-purpose','toefl-listening','lesson-listening-lectures','quiz-bank-v1']::text[], 'published');
insert into public.questions (id, type, section, difficulty, stem_fr, stem_en, passage_id, options, correct, explanation_fr, explanation_en, weight, scoring_map, tags, status) values ('ca8b0d52-604d-4314-bce1-374f578ac2c9', 'audio_qcm', 'listening', 5, 'Quelle conclusion générale le professeur tire-t-il pour les linguistes ?', 'What general conclusion does the professor draw for linguists?', '95481655-2184-4cad-b969-9bc133d7ee35', '["Languages rise when people find them useful, not only when they are imposed.","African languages cannot be used in higher education.","All national languages need government funding to survive.","Trade languages always disappear after one century."]'::jsonb, '[0]'::jsonb, 'Conclusion explicite de l''extrait : les langues s''imposent parce qu''elles sont utiles, pas seulement parce qu''on les impose. Les questions de conclusion ferment souvent les séries du TOEFL Listening.', 'Explicit conclusion: languages rise because people find them worth using.', 1, null, array['academic-lecture','summary','toefl-listening','lesson-listening-lectures','quiz-bank-v1']::text[], 'published');

-- ---------- Test diagnostic V1 (actif) ----------
insert into public.tests (id, name, kind, duration_min, question_ids, scoring, is_active, status) values ('00cd9e63-c45d-4ada-b373-5a69433fb9ac', 'Diagnostic IJAMBO English — V1', 'diagnostic', 25, array['6c2a7c25-6b0a-49aa-987a-20f49fcd07a0','4a16ad7b-67d6-44a0-8d1a-bce2da529a18','9afd7245-bf97-456c-9d08-55ba16b6084f','3ef747f3-b6f4-4175-a077-016d7f276ee1','10597c19-e8b9-4c55-a4f3-40a8a16a4070','5679453c-31bd-4fb0-823a-096c2ba7430c','e29a9e98-3995-4fe2-9eea-db7b5eaf5ebd','2bd7032d-0d46-49ab-9550-7f2d0be03aed','98dbffc9-1742-42d0-87c1-b3979a97a300','2a8012b4-7028-44e5-a27a-f93ef4d751e4','01d81b4a-a7ca-4646-a77d-68fb4377928f','0b40c996-27c0-4373-918b-59e7a8b58b9a','7e5dcd66-1e5a-46ee-ae88-dadfdc1b6f95','98104ae2-d9b8-4644-a1ca-149a36ba7135','92ae6346-6278-40f5-b24b-f6d6230e042a','2aff1b88-46f4-46bc-8948-cce651302274','1958e36f-cf0d-4faf-a99c-16f7f48ece8e','39bddca4-5ed0-4781-9618-8c570fd83fd4','6a9d8b6b-9fe5-4c75-bc64-4748574b82b7','97ea54c2-18f8-43a4-97f3-e086a4c6087e']::uuid[], '{"total_points":100,"bands":[{"min":0,"max":29,"cefr":"A2","toefl_range":[30,45],"program_weeks":16},{"min":30,"max":49,"cefr":"B1-","toefl_range":[46,60],"program_weeks":12},{"min":50,"max":64,"cefr":"B1+","toefl_range":[61,75],"program_weeks":10},{"min":65,"max":79,"cefr":"B2","toefl_range":[76,90],"program_weeks":8},{"min":80,"max":100,"cefr":"C1","toefl_range":[91,110],"program_weeks":5}],"det_recommendation_threshold":60}'::jsonb, true, 'published');

-- ---------- Quiz de leçons (sélection par règles) ----------
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('a7c5f4d9-d7d6-4f87-baea-30cd267d5f28', 'Quiz — Temps du présent', 'quiz_lecon', '[{"tags":["lesson-tenses-1"],"count":4}]'::jsonb, false, 'published');
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('763d0860-8a16-4373-8b99-6850bfd8881f', 'Quiz — Passé et present perfect', 'quiz_lecon', '[{"tags":["lesson-tenses-2","lesson-tenses-3"],"count":5}]'::jsonb, false, 'published');
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('2a0a8fed-741c-42de-b158-d66c33a135cc', 'Quiz — Prépositions', 'quiz_lecon', '[{"tags":["lesson-prepositions"],"count":4}]'::jsonb, false, 'published');
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('c0c7c852-c3e1-4222-9e15-2e27587bd424', 'Quiz — Modaux', 'quiz_lecon', '[{"tags":["lesson-modals"],"count":4}]'::jsonb, false, 'published');
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('7a0647ad-53a0-49b9-8cb3-c24e50b89896', 'Quiz — Reading : Mobile Money', 'quiz_lecon', '[{"tags":["quiz-bank-v1"],"count":4,"section":"reading"}]'::jsonb, false, 'published');
insert into public.tests (id, name, kind, question_rules, is_active, status) values ('a9b83eea-a1e9-4765-8433-98fc680fbb40', 'Quiz — Listening : campus', 'quiz_lecon', '[{"tags":["quiz-bank-v1"],"count":4,"section":"listening"}]'::jsonb, false, 'published');

-- ---------- Formation « Programme TOEFL 10 semaines » ----------
insert into public.courses (id, name, target, description, duration_weeks, status, sort) values ('571b0f46-d218-495a-980e-0f3261e1bca8', 'Programme TOEFL 10 semaines', 'toefl', 'Programme complet de préparation au TOEFL iBT pour francophones : Listening, Reading, Writing, Speaking et stratégie d’examen.', 10, 'published', 0);
insert into public.modules (id, course_id, name, icon, sort) values ('140a60b7-435f-48ba-8b04-db72a2849012', '571b0f46-d218-495a-980e-0f3261e1bca8', 'Listening', '🎧', 0);
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('4d8a0550-c6ba-4671-a260-f2743eb95c85', '140a60b7-435f-48ba-8b04-db72a2849012', 'Comprendre les conversations campus', '# Comprendre les conversations campus

Repérer la situation, le problème et la solution dans une conversation étudiante type TOEFL.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', 'a9b83eea-a1e9-4765-8433-98fc680fbb40', 70, 25, 0, 'published');
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('027355e4-5e56-4fb6-b70e-e56f0180dd0d', '140a60b7-435f-48ba-8b04-db72a2849012', 'Les cours magistraux académiques', '# Les cours magistraux académiques

Identifier le sujet principal, les exemples et la structure d’un extrait de cours.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', '7a0647ad-53a0-49b9-8cb3-c24e50b89896', 70, 25, 1, 'published');
insert into public.modules (id, course_id, name, icon, sort) values ('d7f90d35-9c78-464e-83d6-c41ae35f8377', '571b0f46-d218-495a-980e-0f3261e1bca8', 'Reading', '📖', 1);
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('6be32302-e741-4fb8-9961-2c5fc08e5f07', 'd7f90d35-9c78-464e-83d6-c41ae35f8377', 'Trouver l’idée principale', '# Trouver l’idée principale

Distinguer l’idée centrale des détails de support — le piège n°1 du TOEFL Reading.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', '7a0647ad-53a0-49b9-8cb3-c24e50b89896', 70, 25, 0, 'published');
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('e0cf0546-7748-4af8-9938-3c99ce9450dd', 'd7f90d35-9c78-464e-83d6-c41ae35f8377', 'Vocabulaire en contexte', '# Vocabulaire en contexte

Déduire le sens d’un mot par son contexte sans dictionnaire.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', '2a0a8fed-741c-42de-b158-d66c33a135cc', 70, 25, 1, 'published');
insert into public.modules (id, course_id, name, icon, sort) values ('8aef402e-cdd0-41f1-a0ec-c2b66f5d0025', '571b0f46-d218-495a-980e-0f3261e1bca8', 'Writing', '✍️', 2);
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('6969ead9-2404-4d77-b548-c071e6d1ba5e', '8aef402e-cdd0-41f1-a0ec-c2b66f5d0025', 'Structurer un essai en 30 minutes', '# Structurer un essai en 30 minutes

Le plan en 4 paragraphes : introduction, deux arguments, conclusion.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', 'a7c5f4d9-d7d6-4f87-baea-30cd267d5f28', 70, 25, 0, 'published');
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('6a514e0a-c7dc-4259-abfa-84268b163bd8', '8aef402e-cdd0-41f1-a0ec-c2b66f5d0025', 'Les connecteurs logiques', '# Les connecteurs logiques

However, despite, although : lier ses idées comme au niveau B2+.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', 'c0c7c852-c3e1-4222-9e15-2e27587bd424', 70, 25, 1, 'published');
insert into public.modules (id, course_id, name, icon, sort) values ('a05d914f-c83a-44c8-ab84-0de566c8fd74', '571b0f46-d218-495a-980e-0f3261e1bca8', 'Speaking', '🗣', 3);
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('b957db1b-da42-4cbb-8ec7-d108e4145284', 'a05d914f-c83a-44c8-ab84-0de566c8fd74', 'Parler 45 secondes sans bloquer', '# Parler 45 secondes sans bloquer

La méthode Point-Raison-Exemple pour les questions indépendantes.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', 'a7c5f4d9-d7d6-4f87-baea-30cd267d5f28', 70, 25, 0, 'published');
insert into public.modules (id, course_id, name, icon, sort) values ('b05fdb68-5f49-4c5e-a7e0-4fe7c8563b0b', '571b0f46-d218-495a-980e-0f3261e1bca8', 'Stratégie', '🧭', 4);
insert into public.lessons (id, module_id, title, body_md, quiz_test_id, pass_threshold, est_minutes, sort, status) values ('cd3839c0-f236-4295-bfa1-6d998166f549', 'b05fdb68-5f49-4c5e-a7e0-4fe7c8563b0b', 'Gérer son temps le jour J', '# Gérer son temps le jour J

Rythme par section, questions à sauter, gestion du stress.

## Ce que vous allez apprendre

- La méthode pas à pas, illustrée d''exemples du contexte burundais
- Les pièges typiques pour les francophones
- Un exercice guidé avant le quiz

> **Astuce IJAMBO** : travaillez cette leçon en 2 sessions de 15 minutes plutôt qu''une seule de 30.

*Contenu complet à rédiger dans le back-office (§6.5).*', 'a7c5f4d9-d7d6-4f87-baea-30cd267d5f28', 70, 25, 0, 'published');

-- ---------- Examen blanc TOEFL n°1 ----------
insert into public.exams (id, name, target, sections, status) values ('004107ee-8188-4bae-a7f3-39980cb15204', 'Test blanc TOEFL n°1', 'toefl', '[{"name":"Reading","duration_min":35,"rules":[{"section":"reading","count":8}],"order":0,"instructions_fr":"2 passages académiques. Vous pouvez revenir en arrière dans la section.","instructions_en":"2 academic passages. You may go back within the section."},{"name":"Listening","duration_min":36,"rules":[{"section":"listening","count":8}],"order":1,"instructions_fr":"Conversations et extraits de cours. Une seule écoute par audio.","instructions_en":"Conversations and lecture excerpts. One listen per audio."},{"name":"Writing","duration_min":29,"rules":[{"section":"writing","count":1}],"order":2,"instructions_fr":"Rédigez votre essai dans la zone de texte. Correction par votre coach sous 48 h.","instructions_en":"Write your essay in the text area. Corrected by your coach within 48 h."},{"name":"Speaking","duration_min":16,"rules":[{"section":"speaking","count":1}],"order":3,"instructions_fr":"Enregistrez votre réponse (45 s de préparation, 45 s de parole).","instructions_en":"Record your answer (45 s preparation, 45 s speaking)."}]'::jsonb, 'published');

-- ---------- Formules tarifaires ----------
insert into public.plans (id, name, price_bif, access_days, features, course_ids, exam_quota, coaching_sessions, is_active, sort) values ('ad976c91-ec97-4a4b-8e80-3343d455c6c5', 'Essentiel', 75000, 120, '{"fr":["Programme personnalisé complet (4 sections)","200+ questions avec corrigés en français","2 tests blancs chronométrés","Suivi de progression semaine par semaine"],"en":["Full personalised programme (4 sections)","200+ questions with French explanations","2 timed mock tests","Week-by-week progress tracking"]}'::jsonb, array['571b0f46-d218-495a-980e-0f3261e1bca8']::uuid[], 2, 0, true, 0);
insert into public.plans (id, name, price_bif, access_days, features, course_ids, exam_quota, coaching_sessions, is_active, sort) values ('9065fb16-4c6b-47a7-a959-07509c3ed049', 'Accompagné', 150000, 120, '{"highlight":true,"fr":["Tout le pack Essentiel","4 tests blancs + analyses détaillées","Sessions live de groupe chaque semaine","Correction individuelle Writing & Speaking"],"en":["Everything in Essentiel","4 mock tests + detailed analysis","Weekly live group sessions","Individual Writing & Speaking correction"]}'::jsonb, array['571b0f46-d218-495a-980e-0f3261e1bca8']::uuid[], 4, 0, true, 1);
insert into public.plans (id, name, price_bif, access_days, features, course_ids, exam_quota, coaching_sessions, is_active, sort) values ('e55b9089-0508-4c72-9b5f-6998e72e9514', 'Premium présentiel', 250000, 120, '{"fr":["Tout le pack Accompagné","8 sessions individuelles avec Coach Jacques","Simulation orale complète en conditions réelles","Aide au dossier de bourse (relecture CV/lettre)"],"en":["Everything in Accompagné","8 individual sessions with Coach Jacques","Full oral simulation in real conditions","Scholarship file support (CV/letter review)"]}'::jsonb, array['571b0f46-d218-495a-980e-0f3261e1bca8']::uuid[], 4, 8, true, 2);

-- ---------- Paramètres app ----------
insert into public.app_settings (key, value) values ('lumicash_merchant_code', '{"label":"IJAMBO","code":"40217","ussd":"*163#"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('whatsapp_numbers', '{"support":"+25779000000","admin":"+25779000001"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('det_threshold', '60'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('live_session_links', '{"speaking":"","writing":""}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('home_texts', '{"fr":{"greeting":"Amahoro ! 👋","sub":"Découvrez votre niveau réel en 25 minutes et recevez votre plan de préparation personnalisé jusqu''au jour de l''examen."},"en":{"greeting":"Amahoro! 👋","sub":"Discover your real level in 25 minutes and receive your personalised preparation plan all the way to exam day."}}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('home_stats', '{"questions":"200+","mock_tests":"4","max_data":"2 Go"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.app_settings (key, value) values ('diagnostic_unlocks', '[]'::jsonb) on conflict (key) do update set value = excluded.value;
